language:
  - python

os:
  - linux
#- windows
#- osx

python:
  - '2.7'
  - '3.8'

matrix:
  include:
    - python: '3.8'
      name: 'Testing auxiliary tools'
      script: python -tt -m compileall -f HersheyFonts_tools

script:
  - python -tt -m compileall -f HersheyFonts
  - python setup.py sdist

notifications:
  email: false